language: python
python:
  - "2.7"
sudo: required
addons:
  apt_packages:
    - swig

# command to install dependencies
install: "bash ./YurasSetupTravis.sh"
script: "find -name '*.py' | xargs -i nosetests {}"
