language: python
python:
  - "2.7"
sudo: false
addons:
  apt_packages:
    - swig 
  
# command to install dependencies
install: "bash ./YurasSetupTravis.sh"
script: "find -name '*.py' | xargs -i nosetests {}"